import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;

public class EventModel implements ActionListener{
    // Give life to the user inteface, Interacts with the UI`
    /* We're discussing Event Model */

    /*
     * We have EVENT SOURCE; the trigger or action taken like clicking the mouse.
     * EVENT LISTENER- Listens for the action. Also called action listener
     * EVENT HANDLER- Assassin, does the job.
     * 
     * Events are generated by the following sources; 
     * button, frame (open or close) or combo box. They have event listener
     */

    JButton button = new JButton("NEXT");
    JFrame frame = new JFrame("My Frame");
    
    public void testingButt() {
        frame.setVisible(true);
        frame.setSize(200, 300);
        frame.setLayout(null);
        
        button.addActionListener(this);
        button.setBackground(Color.GREEN);
        button.setForeground(Color.WHITE);
        frame.add(button);
    }
    public static void main(String[] args) {
        EventModel em = new EventModel();
        em.testingButt();
    }
    @Override
    public void actionPerformed(ActionEvent e) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'actionPerformed'");
    }
}
